Word Embedding Techniques using Embedding Layer in Keras

In [2]:
from tensorflow import keras
from keras.preprocessing.text import one_hot

In [3]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
type(sent)

list

In [6]:
# vocab size
voc_size = 500

One Hot Representation

In [7]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[498, 99, 333, 319], [498, 99, 333, 233], [498, 390, 333, 124], [402, 217, 174, 90, 343], [402, 217, 174, 90, 314], [284, 498, 343, 333, 352], [493, 267, 44, 90]]


__Word Emedding Representation__

In [12]:
from tensorflow import keras
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 498  99 333 319]
 [  0   0   0   0 498  99 333 233]
 [  0   0   0   0 498 390 333 124]
 [  0   0   0 402 217 174  90 343]
 [  0   0   0 402 217 174  90 314]
 [  0   0   0 284 498 343 333 352]
 [  0   0   0   0 493 267  44  90]]


In [13]:
dim = 10

model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 1s 559ms/step
[[[ 0.03670524  0.02664315 -0.01177001 -0.04697393  0.0206976
   -0.02940309  0.04099554 -0.00592402 -0.01275196  0.04127261]
  [ 0.03670524  0.02664315 -0.01177001 -0.04697393  0.0206976
   -0.02940309  0.04099554 -0.00592402 -0.01275196  0.04127261]
  [ 0.03670524  0.02664315 -0.01177001 -0.04697393  0.0206976
   -0.02940309  0.04099554 -0.00592402 -0.01275196  0.04127261]
  [ 0.03670524  0.02664315 -0.01177001 -0.04697393  0.0206976
   -0.02940309  0.04099554 -0.00592402 -0.01275196  0.04127261]
  [-0.04715339  0.02126643  0.00238788  0.03589046 -0.01214836
    0.03204225 -0.02488565  0.03408204 -0.02713504 -0.03965374]
  [ 0.01668474 -0.02510854  0.01032763 -0.04696578 -0.04852024
    0.03217289 -0.01336507 -0.0352345   0.03493751 -0.04244255]
  [ 0.01148667 -0.0299767   0.03444434 -0.0296939   0.03655149
    0.01937398  0.02083868 -0.01908215  0.0038317  -0.02379987]
  [-0.03250681 -0.03707595  0.0336302   0.04596574 -0.01159375

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 56ms/step


array([[ 0.03670524,  0.02664315, -0.01177001, -0.04697393,  0.0206976 ,
        -0.02940309,  0.04099554, -0.00592402, -0.01275196,  0.04127261],
       [ 0.03670524,  0.02664315, -0.01177001, -0.04697393,  0.0206976 ,
        -0.02940309,  0.04099554, -0.00592402, -0.01275196,  0.04127261],
       [ 0.03670524,  0.02664315, -0.01177001, -0.04697393,  0.0206976 ,
        -0.02940309,  0.04099554, -0.00592402, -0.01275196,  0.04127261],
       [ 0.03670524,  0.02664315, -0.01177001, -0.04697393,  0.0206976 ,
        -0.02940309,  0.04099554, -0.00592402, -0.01275196,  0.04127261],
       [-0.04715339,  0.02126643,  0.00238788,  0.03589046, -0.01214836,
         0.03204225, -0.02488565,  0.03408204, -0.02713504, -0.03965374],
       [ 0.01668474, -0.02510854,  0.01032763, -0.04696578, -0.04852024,
         0.03217289, -0.01336507, -0.0352345 ,  0.03493751, -0.04244255],
       [ 0.01148667, -0.0299767 ,  0.03444434, -0.0296939 ,  0.03655149,
         0.01937398,  0.02083868, -0.01908215

In [16]:
embedded_docs[0]

array([  0,   0,   0,   0, 498,  99, 333, 319])