In [2]:
from tensorflow import keras
from keras.preprocessing.text import one_hot

In [3]:
# sentence
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'understand the meaning of words',
    'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# vocabulary
voc_size = 10000

__One Hot Representation__

In [6]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[203, 8862, 2004, 6443], [203, 8862, 2004, 1600], [203, 3731, 2004, 4542], [9508, 1979, 5400, 9373, 1203], [5646, 203, 491, 2004, 6312], [50, 3312, 1247, 9373]]


__Word Embedding Representation__

In [7]:
from tensorflow import keras
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import numpy as np

In [8]:
sent_length = 8
embedder_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedder_docs)

[[   0    0    0    0  203 8862 2004 6443]
 [   0    0    0    0  203 8862 2004 1600]
 [   0    0    0    0  203 3731 2004 4542]
 [   0    0    0 9508 1979 5400 9373 1203]
 [   0    0    0 5646  203  491 2004 6312]
 [   0    0    0    0   50 3312 1247 9373]]


In [9]:
dim = 15

In [10]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
print(model.predict(embedder_docs))

1/1 [==============================] - 0s 339ms/step
[[[-4.37067151e-02  4.50175665e-02 -2.50480901e-02 -4.54440713e-02
   -1.67133585e-02 -4.73042838e-02  2.37346403e-02  1.92618035e-02
    2.48025097e-02 -2.75735501e-02]
  [-4.37067151e-02  4.50175665e-02 -2.50480901e-02 -4.54440713e-02
   -1.67133585e-02 -4.73042838e-02  2.37346403e-02  1.92618035e-02
    2.48025097e-02 -2.75735501e-02]
  [-4.37067151e-02  4.50175665e-02 -2.50480901e-02 -4.54440713e-02
   -1.67133585e-02 -4.73042838e-02  2.37346403e-02  1.92618035e-02
    2.48025097e-02 -2.75735501e-02]
  [-4.37067151e-02  4.50175665e-02 -2.50480901e-02 -4.54440713e-02
   -1.67133585e-02 -4.73042838e-02  2.37346403e-02  1.92618035e-02
    2.48025097e-02 -2.75735501e-02]
  [-3.65935639e-03  4.67092730e-02  2.46063955e-02 -3.81909683e-03
   -4.43205722e-02 -2.73354407e-02 -3.87496948e-02  3.93020548e-02
   -1.99656840e-02 -3.27896103e-02]
  [-3.57527956e-02  1.53913535e-02  1.76047720e-02  3.10441740e-02
   -3.34452391e-02  4.50908206

In [13]:
embedder_docs[0]

array([   0,    0,    0,    0,  203, 8862, 2004, 6443])

In [14]:
print(model.predict(embedder_docs)[0])

1/1 [==============================] - 0s 61ms/step
[[-4.37067151e-02  4.50175665e-02 -2.50480901e-02 -4.54440713e-02
  -1.67133585e-02 -4.73042838e-02  2.37346403e-02  1.92618035e-02
   2.48025097e-02 -2.75735501e-02]
 [-4.37067151e-02  4.50175665e-02 -2.50480901e-02 -4.54440713e-02
  -1.67133585e-02 -4.73042838e-02  2.37346403e-02  1.92618035e-02
   2.48025097e-02 -2.75735501e-02]
 [-4.37067151e-02  4.50175665e-02 -2.50480901e-02 -4.54440713e-02
  -1.67133585e-02 -4.73042838e-02  2.37346403e-02  1.92618035e-02
   2.48025097e-02 -2.75735501e-02]
 [-4.37067151e-02  4.50175665e-02 -2.50480901e-02 -4.54440713e-02
  -1.67133585e-02 -4.73042838e-02  2.37346403e-02  1.92618035e-02
   2.48025097e-02 -2.75735501e-02]
 [-3.65935639e-03  4.67092730e-02  2.46063955e-02 -3.81909683e-03
  -4.43205722e-02 -2.73354407e-02 -3.87496948e-02  3.93020548e-02
  -1.99656840e-02 -3.27896103e-02]
 [-3.57527956e-02  1.53913535e-02  1.76047720e-02  3.10441740e-02
  -3.34452391e-02  4.50908206e-02  1.98313706e-