In [1]:
import pandas as pd

messages = pd.read_csv('SMSSpamCollection', sep='\t',names=["label", "message"])
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [2]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\emon1\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [3]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [4]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
print(corpus)

[', .. ... ...', '... ...', "2 21 2005. 87121 ( ) & ' 08452810075 18'", '... ...', "' ,", "' 3 ' ! ' ? ! , £1.50", '. .', "' ( )' . *9", '!! £900 ! 09061701461. 341. 12 .', '11 ? ! 08002986030', "' ' , ? ' .", '! 100 20,000 > 11 87575. 150 / , 6 , 16+ 4', '! 1 £100,000 ! : : 81010 & . . 4403 1 7 18', "' . . .", '!!', ': , >> :// . . ? =', "... ' :)", '2 ... . .', '\x92 . \x92', '- / . 87077 87077 : , 4 /ú1.20 36504 45 16+', '?', '‘ 2', 'ü ... ...', '. 3 . ?', '. ?', ". ' . . . ' .", '.', "? ? ? ' ? ?", "' & ; ' , ' '", '. . ! ?', "' , ' '", "2 . . 2! ' ! . ?", '.', '?', '£5/ .', '... ü ... 2 8', ", ' '", '', '... ...', "! ' ? ' . ' !", '. . .', '? , , ... ... ... ...', '07732584351 - - = + . 08000930705', '?', '! . & ;#& ; ...', '.. ..', "' .", ', ?', ", '", "' . ' . ' . .", '. .', '& ;#& ; , & ;#& ;', "'", '. . , " ". \' \' \' . \' . \' .', '. : . ? ?', '? @ & ; & ;', '! 1 2 . 09061209465 ! , 3, 3, 4 ! 420- 4-5 . 150 . !', ", ' .", '', '.. .', "$1 . ' . .", '. .', '', ', ?', '. .', ',

In [7]:
# creating the bag of words model
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500)
x = cv.fit_transform(corpus).toarray()

In [12]:
y = pd.get_dummies(messages['label'])
y = y.iloc[:,1].values
y

array([False, False,  True, ..., False, False, False])

In [14]:
# train test split
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)

In [15]:
# training model using naive bayes classifier
from sklearn.naive_bayes import MultinomialNB

spam_detect_model = MultinomialNB().fit(x_train,y_train)

In [17]:
y_pred = spam_detect_model.predict(x_test)
y_pred

array([False, False, False, ..., False,  True, False])

In [20]:
from sklearn.metrics import confusion_matrix

confussion_matrix = confusion_matrix(y_test,y_pred)
confussion_matrix

array([[954,   1],
       [ 89,  71]], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score_test = accuracy_score(y_test,y_pred)
accuracy_score_test

0.9192825112107623